// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Actualité documents
 */
interface ActualiteDocumentData {
  /**
   * Titre field in *Actualité*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: actualite.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Extrait field in *Actualité*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: actualite.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Date field in *Actualité*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: actualite.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Image field in *Actualité*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: actualite.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Contenu field in *Actualité*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: actualite.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Actualité document from Prismic
 *
 * - **API ID**: `actualite`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ActualiteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ActualiteDocumentData>,
    "actualite",
    Lang
  >;

/**
 * Primary content in *Homepage → Slice Zone → Hero → Primary*
 */
export interface HomepageDocumentDataBodyHeroSlicePrimary {
  /**
   * Sur-titre field in *Homepage → Slice Zone → Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Association de la Fondation du Prado
   * - **API ID Path**: homepage.body[].hero.primary.surtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  surtitle: prismic.KeyTextField;

  /**
   * Titre principal field in *Homepage → Slice Zone → Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].hero.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Homepage → Slice Zone → Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].hero.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA primaire - Texte field in *Homepage → Slice Zone → Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].hero.primary.cta_primary_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_primary_label: prismic.KeyTextField;

  /**
   * CTA primaire - Lien field in *Homepage → Slice Zone → Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].hero.primary.cta_primary_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_primary_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * CTA secondaire - Texte field in *Homepage → Slice Zone → Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].hero.primary.cta_secondary_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_secondary_label: prismic.KeyTextField;

  /**
   * CTA secondaire - Lien field in *Homepage → Slice Zone → Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].hero.primary.cta_secondary_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_secondary_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Slice for *Homepage → Slice Zone*
 */
export type HomepageDocumentDataBodyHeroSlice = prismic.Slice<
  "hero",
  Simplify<HomepageDocumentDataBodyHeroSlicePrimary>,
  never
>;

/**
 * Primary content in *Homepage → Slice Zone → Programmes → Primary*
 */
export interface HomepageDocumentDataBodyProgrammesSlicePrimary {
  /**
   * Titre de section field in *Homepage → Slice Zone → Programmes → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].programmes.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;
}

/**
 * Item content in *Homepage → Slice Zone → Programmes → Items*
 */
export interface HomepageDocumentDataBodyProgrammesSliceItem {
  /**
   * Slug (ancre) field in *Homepage → Slice Zone → Programmes → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: jeunes, foodtruck, etc.
   * - **API ID Path**: homepage.body[].programmes.items.slug
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  slug: prismic.KeyTextField;

  /**
   * Titre complet field in *Homepage → Slice Zone → Programmes → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].programmes.items.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Titre court (sidebar) field in *Homepage → Slice Zone → Programmes → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].programmes.items.short_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  short_title: prismic.KeyTextField;

  /**
   * Icône field in *Homepage → Slice Zone → Programmes → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].programmes.items.icon_name
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon_name: prismic.SelectField<
    | "Users"
    | "Truck"
    | "Heart"
    | "BookOpen"
    | "UtensilsCrossed"
    | "HeartHandshake"
    | "Puzzle"
  >;

  /**
   * Couleur field in *Homepage → Slice Zone → Programmes → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].programmes.items.brand_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  brand_color: prismic.ColorField;

  /**
   * Description field in *Homepage → Slice Zone → Programmes → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].programmes.items.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA 1 - Texte field in *Homepage → Slice Zone → Programmes → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].programmes.items.cta_1_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_1_label: prismic.KeyTextField;

  /**
   * CTA 1 - Lien field in *Homepage → Slice Zone → Programmes → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].programmes.items.cta_1_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_1_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * CTA 2 - Texte field in *Homepage → Slice Zone → Programmes → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].programmes.items.cta_2_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_2_label: prismic.KeyTextField;

  /**
   * CTA 2 - Lien field in *Homepage → Slice Zone → Programmes → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].programmes.items.cta_2_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_2_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * CTA 3 - Texte field in *Homepage → Slice Zone → Programmes → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].programmes.items.cta_3_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_3_label: prismic.KeyTextField;

  /**
   * CTA 3 - Lien field in *Homepage → Slice Zone → Programmes → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].programmes.items.cta_3_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_3_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Slice for *Homepage → Slice Zone*
 */
export type HomepageDocumentDataBodyProgrammesSlice = prismic.Slice<
  "programmes",
  Simplify<HomepageDocumentDataBodyProgrammesSlicePrimary>,
  Simplify<HomepageDocumentDataBodyProgrammesSliceItem>
>;

/**
 * Primary content in *Homepage → Slice Zone → Missions → Primary*
 */
export interface HomepageDocumentDataBodyMissionsSlicePrimary {
  /**
   * Titre de section field in *Homepage → Slice Zone → Missions → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].missions.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Texte d'introduction field in *Homepage → Slice Zone → Missions → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].missions.primary.intro_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro_text: prismic.RichTextField;

  /**
   * Titre colonne jeunes field in *Homepage → Slice Zone → Missions → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].missions.primary.jeunes_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  jeunes_title: prismic.KeyTextField;

  /**
   * Titre colonne familles field in *Homepage → Slice Zone → Missions → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].missions.primary.familles_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  familles_title: prismic.KeyTextField;
}

/**
 * Item content in *Homepage → Slice Zone → Missions → Items*
 */
export interface HomepageDocumentDataBodyMissionsSliceItem {
  /**
   * Catégorie field in *Homepage → Slice Zone → Missions → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].missions.items.category
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<"jeunes" | "familles">;

  /**
   * Texte de la mission field in *Homepage → Slice Zone → Missions → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].missions.items.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Slice for *Homepage → Slice Zone*
 */
export type HomepageDocumentDataBodyMissionsSlice = prismic.Slice<
  "missions",
  Simplify<HomepageDocumentDataBodyMissionsSlicePrimary>,
  Simplify<HomepageDocumentDataBodyMissionsSliceItem>
>;

/**
 * Primary content in *Homepage → Slice Zone → Chiffres d'impact → Primary*
 */
export interface HomepageDocumentDataBodyImpactSlicePrimary {
  /**
   * Titre de section field in *Homepage → Slice Zone → Chiffres d'impact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].impact.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;
}

/**
 * Item content in *Homepage → Slice Zone → Chiffres d'impact → Items*
 */
export interface HomepageDocumentDataBodyImpactSliceItem {
  /**
   * Valeur numérique field in *Homepage → Slice Zone → Chiffres d'impact → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].impact.items.value
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  value: prismic.NumberField;

  /**
   * Suffixe (+, %, etc.) field in *Homepage → Slice Zone → Chiffres d'impact → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].impact.items.suffix
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  suffix: prismic.KeyTextField;

  /**
   * Libellé field in *Homepage → Slice Zone → Chiffres d'impact → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].impact.items.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Couleur field in *Homepage → Slice Zone → Chiffres d'impact → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].impact.items.color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color: prismic.ColorField;
}

/**
 * Slice for *Homepage → Slice Zone*
 */
export type HomepageDocumentDataBodyImpactSlice = prismic.Slice<
  "impact",
  Simplify<HomepageDocumentDataBodyImpactSlicePrimary>,
  Simplify<HomepageDocumentDataBodyImpactSliceItem>
>;

/**
 * Primary content in *Homepage → Slice Zone → Étapes → Primary*
 */
export interface HomepageDocumentDataBodyStepsSlicePrimary {
  /**
   * Titre de section field in *Homepage → Slice Zone → Étapes → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].steps.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * CTA - Texte field in *Homepage → Slice Zone → Étapes → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].steps.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA - Lien field in *Homepage → Slice Zone → Étapes → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].steps.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Texte de réassurance field in *Homepage → Slice Zone → Étapes → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].steps.primary.reassurance_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  reassurance_text: prismic.KeyTextField;
}

/**
 * Item content in *Homepage → Slice Zone → Étapes → Items*
 */
export interface HomepageDocumentDataBodyStepsSliceItem {
  /**
   * Numéro field in *Homepage → Slice Zone → Étapes → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 01
   * - **API ID Path**: homepage.body[].steps.items.step_number
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  step_number: prismic.KeyTextField;

  /**
   * Titre field in *Homepage → Slice Zone → Étapes → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].steps.items.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Homepage → Slice Zone → Étapes → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].steps.items.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Slice for *Homepage → Slice Zone*
 */
export type HomepageDocumentDataBodyStepsSlice = prismic.Slice<
  "steps",
  Simplify<HomepageDocumentDataBodyStepsSlicePrimary>,
  Simplify<HomepageDocumentDataBodyStepsSliceItem>
>;

/**
 * Primary content in *Homepage → Slice Zone → Témoignages → Primary*
 */
export interface HomepageDocumentDataBodyTestimonialsSlicePrimary {
  /**
   * Titre de section field in *Homepage → Slice Zone → Témoignages → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].testimonials.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;
}

/**
 * Item content in *Homepage → Slice Zone → Témoignages → Items*
 */
export interface HomepageDocumentDataBodyTestimonialsSliceItem {
  /**
   * Citation field in *Homepage → Slice Zone → Témoignages → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].testimonials.items.quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Nom field in *Homepage → Slice Zone → Témoignages → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].testimonials.items.author_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Rôle field in *Homepage → Slice Zone → Témoignages → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].testimonials.items.author_role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_role: prismic.KeyTextField;

  /**
   * Organisation field in *Homepage → Slice Zone → Témoignages → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].testimonials.items.author_org
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_org: prismic.KeyTextField;
}

/**
 * Slice for *Homepage → Slice Zone*
 */
export type HomepageDocumentDataBodyTestimonialsSlice = prismic.Slice<
  "testimonials",
  Simplify<HomepageDocumentDataBodyTestimonialsSlicePrimary>,
  Simplify<HomepageDocumentDataBodyTestimonialsSliceItem>
>;

/**
 * Primary content in *Homepage → Slice Zone → FAQ → Primary*
 */
export interface HomepageDocumentDataBodyFaqSlicePrimary {
  /**
   * Titre de section field in *Homepage → Slice Zone → FAQ → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].faq.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;
}

/**
 * Item content in *Homepage → Slice Zone → FAQ → Items*
 */
export interface HomepageDocumentDataBodyFaqSliceItem {
  /**
   * Question field in *Homepage → Slice Zone → FAQ → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].faq.items.question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Réponse field in *Homepage → Slice Zone → FAQ → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].faq.items.answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Slice for *Homepage → Slice Zone*
 */
export type HomepageDocumentDataBodyFaqSlice = prismic.Slice<
  "faq",
  Simplify<HomepageDocumentDataBodyFaqSlicePrimary>,
  Simplify<HomepageDocumentDataBodyFaqSliceItem>
>;

/**
 * Primary content in *Homepage → Slice Zone → Partenaires → Primary*
 */
export interface HomepageDocumentDataBodyPartnersSlicePrimary {
  /**
   * Titre de section field in *Homepage → Slice Zone → Partenaires → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].partners.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Sous-titre field in *Homepage → Slice Zone → Partenaires → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].partners.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Item content in *Homepage → Slice Zone → Partenaires → Items*
 */
export interface HomepageDocumentDataBodyPartnersSliceItem {
  /**
   * Nom du partenaire field in *Homepage → Slice Zone → Partenaires → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].partners.items.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Logo field in *Homepage → Slice Zone → Partenaires → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].partners.items.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Site web field in *Homepage → Slice Zone → Partenaires → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].partners.items.url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Slice for *Homepage → Slice Zone*
 */
export type HomepageDocumentDataBodyPartnersSlice = prismic.Slice<
  "partners",
  Simplify<HomepageDocumentDataBodyPartnersSlicePrimary>,
  Simplify<HomepageDocumentDataBodyPartnersSliceItem>
>;

/**
 * Primary content in *Homepage → Slice Zone → En savoir plus → Primary*
 */
export interface HomepageDocumentDataBodyEnSavoirPlusSlicePrimary {
  /**
   * Titre de section field in *Homepage → Slice Zone → En savoir plus → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].en_savoir_plus.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;
}

/**
 * Item content in *Homepage → Slice Zone → En savoir plus → Items*
 */
export interface HomepageDocumentDataBodyEnSavoirPlusSliceItem {
  /**
   * Titre field in *Homepage → Slice Zone → En savoir plus → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].en_savoir_plus.items.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Homepage → Slice Zone → En savoir plus → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].en_savoir_plus.items.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Texte du lien field in *Homepage → Slice Zone → En savoir plus → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].en_savoir_plus.items.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Lien field in *Homepage → Slice Zone → En savoir plus → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].en_savoir_plus.items.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Slice for *Homepage → Slice Zone*
 */
export type HomepageDocumentDataBodyEnSavoirPlusSlice = prismic.Slice<
  "en_savoir_plus",
  Simplify<HomepageDocumentDataBodyEnSavoirPlusSlicePrimary>,
  Simplify<HomepageDocumentDataBodyEnSavoirPlusSliceItem>
>;

/**
 * Primary content in *Homepage → Slice Zone → CTA Final → Primary*
 */
export interface HomepageDocumentDataBodyCtaFinalSlicePrimary {
  /**
   * Titre field in *Homepage → Slice Zone → CTA Final → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].cta_final.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Homepage → Slice Zone → CTA Final → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].cta_final.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA primaire - Texte field in *Homepage → Slice Zone → CTA Final → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].cta_final.primary.cta_primary_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_primary_label: prismic.KeyTextField;

  /**
   * CTA primaire - Lien field in *Homepage → Slice Zone → CTA Final → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].cta_final.primary.cta_primary_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_primary_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * CTA secondaire - Texte field in *Homepage → Slice Zone → CTA Final → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].cta_final.primary.cta_secondary_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_secondary_label: prismic.KeyTextField;

  /**
   * CTA secondaire - Lien field in *Homepage → Slice Zone → CTA Final → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].cta_final.primary.cta_secondary_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_secondary_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Texte de pied field in *Homepage → Slice Zone → CTA Final → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].cta_final.primary.footer_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_text: prismic.KeyTextField;
}

/**
 * Slice for *Homepage → Slice Zone*
 */
export type HomepageDocumentDataBodyCtaFinalSlice = prismic.Slice<
  "cta_final",
  Simplify<HomepageDocumentDataBodyCtaFinalSlicePrimary>,
  never
>;

type HomepageDocumentDataBodySlice =
  | HomepageDocumentDataBodyHeroSlice
  | HomepageDocumentDataBodyProgrammesSlice
  | HomepageDocumentDataBodyMissionsSlice
  | HomepageDocumentDataBodyImpactSlice
  | HomepageDocumentDataBodyStepsSlice
  | HomepageDocumentDataBodyTestimonialsSlice
  | HomepageDocumentDataBodyFaqSlice
  | HomepageDocumentDataBodyPartnersSlice
  | HomepageDocumentDataBodyEnSavoirPlusSlice
  | HomepageDocumentDataBodyCtaFinalSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre SEO de la page d'accueil
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description SEO
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.og_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>; /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  body: prismic.SliceZone<HomepageDocumentDataBodySlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = ActualiteDocument | HomepageDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ActualiteDocument,
      ActualiteDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataBodyHeroSlicePrimary,
      HomepageDocumentDataBodyProgrammesSlicePrimary,
      HomepageDocumentDataBodyProgrammesSliceItem,
      HomepageDocumentDataBodyMissionsSlicePrimary,
      HomepageDocumentDataBodyMissionsSliceItem,
      HomepageDocumentDataBodyImpactSlicePrimary,
      HomepageDocumentDataBodyImpactSliceItem,
      HomepageDocumentDataBodyStepsSlicePrimary,
      HomepageDocumentDataBodyStepsSliceItem,
      HomepageDocumentDataBodyTestimonialsSlicePrimary,
      HomepageDocumentDataBodyTestimonialsSliceItem,
      HomepageDocumentDataBodyFaqSlicePrimary,
      HomepageDocumentDataBodyFaqSliceItem,
      HomepageDocumentDataBodyPartnersSlicePrimary,
      HomepageDocumentDataBodyPartnersSliceItem,
      HomepageDocumentDataBodyEnSavoirPlusSlicePrimary,
      HomepageDocumentDataBodyEnSavoirPlusSliceItem,
      HomepageDocumentDataBodyCtaFinalSlicePrimary,
      HomepageDocumentDataBodySlice,
      AllDocumentTypes,
    };
  }
}
